services:
  bot:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./html/:/var/www/html/:rw
    depends_on:
      - bot


  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certs:/etc/letsencrypt
      - ./static:/var/www/html  # Доступ к статическим файлам для проверки
    command: >
      certonly --webroot 
      --webroot-path=/var/www/html 
      --email ${EMAIL} 
      --agree-tos 
      --no-eff-email 
      -d ${DOMAIN}

volumes:
  postgres_data: